backend:
  name: git-gateway

media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "posts"
    label: "Aktuality"
    folder: "content/posts"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Název", name: "title", widget: "string" }
      - {
          label: "Datum zveřejnění",
          name: "date",
          widget: "datetime",
          date_format: "DD.MM.YYYY",
          time_format: "HH:mm",
          format: "LLL",
        }
      - { label: "Obsah", name: "content", widget: "markdown" }
