backend:
  name: git-gateway

media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "posts"
    label: "Aktuality"
    folder: "content/posts"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Název", name: "title", widget: "string" }
      - {
          label: "Datum zveřejnění",
          name: "date",
          widget: "datetime",
          date_format: "DD.MM.YYYY",
          time_format: "HH:mm",
          format: "LLL",
        }
      - label: "Obrázky"
        name: "images"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: true
      - {
          label: "YouTube video embed URL",
          name: "youtube_video_embed_url",
          widget: "string",
          required: false,
        }
      - { label: "Obsah", name: "content", widget: "markdown" }
  - name: "contact-info"
    label: "Kontaktní informace"
    folder: "content/contact-info"
    create: true
    fields:
      - { label: "Název", name: "title", widget: "string" }
      - { label: "IČO", name: "ico", widget: "string", required: false }
      - { label: "Telefon", name: "phone", widget: "number" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Adresa", name: "address", widget: "string" }
      - {
          label: "Google maps embed URL",
          name: "google_maps_embed_url",
          widget: "string",
          required: false,
        }
      - label: Otevírací hodiny
        name: openingHours
        widget: list
        fields:
          - label: Pondělí
            name: monday
            widget: list
            fields:
              - label: "Od"
                name: "from"
                widget: "select"
                options: &openingHoursIntervals
                  - "00:00"
                  - "00:15"
                  - "00:30"
                  - "00:45"
                  - "01:00"
                  - "01:15"
                  - "01:30"
                  - "01:45"
                  - "02:00"
                  - "02:15"
                  - "02:30"
                  - "02:45"
                  - "03:00"
                  - "03:15"
                  - "03:30"
                  - "03:45"
                  - "04:00"
                  - "04:15"
                  - "04:30"
                  - "04:45"
                  - "05:00"
                  - "05:15"
                  - "05:30"
                  - "05:45"
                  - "06:00"
                  - "06:15"
                  - "06:30"
                  - "06:45"
                  - "07:00"
                  - "07:15"
                  - "07:30"
                  - "07:45"
                  - "08:00"
                  - "08:15"
                  - "08:30"
                  - "08:45"
                  - "09:00"
                  - "09:15"
                  - "09:30"
                  - "09:45"
                  - "10:00"
                  - "10:15"
                  - "10:30"
                  - "10:45"
                  - "11:00"
                  - "11:15"
                  - "11:30"
                  - "11:45"
                  - "12:00"
                  - "12:15"
                  - "12:30"
                  - "12:45"
                  - "13:00"
                  - "13:15"
                  - "13:30"
                  - "13:45"
                  - "14:00"
                  - "14:15"
                  - "14:30"
                  - "14:45"
                  - "15:00"
                  - "15:15"
                  - "15:30"
                  - "15:45"
                  - "16:00"
                  - "16:15"
                  - "16:30"
                  - "16:45"
                  - "17:00"
                  - "17:15"
                  - "17:30"
                  - "17:45"
                  - "18:00"
                  - "18:15"
                  - "18:30"
                  - "18:45"
                  - "19:00"
                  - "19:15"
                  - "19:30"
                  - "19:45"
                  - "20:00"
                  - "20:15"
                  - "20:30"
                  - "20:45"
                  - "21:00"
                  - "21:15"
                  - "21:30"
                  - "21:45"
                  - "22:00"
                  - "22:15"
                  - "22:30"
                  - "22:45"
                  - "23:00"
                  - "23:15"
                  - "23:30"
                  - "23:45"
              - label: "Do"
                name: "to"
                widget: "select"
                options: *openingHoursIntervals
          - label: Úterý
            name: tuesday
            widget: list
            fields:
              - label: "Od"
                name: "from"
                widget: "select"
                options: *openingHoursIntervals
              - label: "Do"
                name: "to"
                widget: "select"
                options: *openingHoursIntervals
          - label: Středa
            name: Wednesday
            widget: list
            fields:
              - label: "Od"
                name: "from"
                widget: "select"
                options: *openingHoursIntervals
              - label: "Do"
                name: "to"
                widget: "select"
                options: *openingHoursIntervals
          - label: Čtvrtek
            name: Thursday
            widget: list
            fields:
              - label: "Od"
                name: "from"
                widget: "select"
                options: *openingHoursIntervals
              - label: "Do"
                name: "to"
                widget: "select"
                options: *openingHoursIntervals
          - label: Pátek
            name: Friday
            widget: list
            fields:
              - label: "Od"
                name: "from"
                widget: "select"
                options: *openingHoursIntervals
              - label: "Do"
                name: "to"
                widget: "select"
                options: *openingHoursIntervals
          - label: Sobota
            name: Saturday
            widget: list
            fields:
              - label: "Od"
                name: "from"
                widget: "select"
                options: *openingHoursIntervals
              - label: "Do"
                name: "to"
                widget: "select"
                options: *openingHoursIntervals
          - label: Neděle
            name: Sunday
            widget: list
            fields:
              - label: "Od"
                name: "from"
                widget: "select"
                options: *openingHoursIntervals
              - label: "Do"
                name: "to"
                widget: "select"
                options: *openingHoursIntervals
      - label: Sociální sítě
        name: socials
        widget: list
        fields:
          - { label: Facebook, name: facebook, widget: string, required: false }
          - {
              label: Instagram,
              name: instagram,
              widget: string,
              required: false,
            }
          - { label: Twitter, name: twitter, widget: string, required: false }
          - { label: YouTube, name: youtube, widget: string, required: false }
          - { label: Snapchat, name: snapchat, widget: string, required: false }
          - {
              label: Tripadvisor,
              name: tripadvisor,
              widget: string,
              required: false,
            }
